INSERT INTO Customers (customers_customernumber, customername, contactfirstname, contactlastname, phonenumber, address, city, postalcode, country) VALUES (1, 'John Doe Inc.', 'John', 'Doe', '555-12-34-61', '13 Grove Rd.', 'Kansas City, MO', '64030', 'United States');
INSERT INTO Customers (customers_customernumber, customername, contactfirstname, contactlastname, phonenumber, address, city, postalcode, country) VALUES (2, 'Bradbury Shaw Ltd', 'Thomas', 'Bradbury', '08-231-66-23', '78 Farrington Estate', 'Birmingham', '3A C23', 'United Kingdom');
INSERT INTO Customers (customers_customernumber, customername, contactfirstname, contactlastname, phonenumber, address, city, postalcode, country) VALUES (3, 'German Steel Inc', 'Rudolf', 'Springer', '1-32-264-23-61', 'Torenweg 112', 'Duisburg', '002351', 'Germany');
INSERT INTO Customers (customers_customernumber, customername, contactfirstname, contactlastname, phonenumber, address, city, postalcode, country) VALUES (4, 'Koninklijke BAM', 'Guido', 'van Volkem', '06-232-26-7112', 'Stationsplein 23', 'Amersfoort', '2734VZ', 'The Netherlands');
INSERT INTO Product (product_id, productname, productvendor, productdescription, productquantity, productprice) VALUES (1, 'Steel Beam', 'PHILIPS', 'A 2m long steel beam', 23, 860.00);
INSERT INTO Product (product_id, productname, productvendor, productdescription, productquantity, productprice) VALUES (2, 'Pliers', 'BOSCH', 'Handy pliers', 662, 17.50);
INSERT INTO Product (product_id, productname, productvendor, productdescription, productquantity, productprice) VALUES (3, 'Hammer and Nails', 'CHEVRON', 'Cant get more basic than that', 2320, 8.20);
INSERT INTO Product (product_id, productname, productvendor, productdescription, productquantity, productprice) VALUES (4, 'Chainsaw', 'HUSQVARNA', 'Good for cutting down trees', 53, 499.99);
INSERT INTO Product (product_id, productname, productvendor, productdescription, productquantity, productprice) VALUES (5, 'Rusty bucket', 'ELECTROLUX', 'I wouldnt buy it', 1, 7.50);
INSERT INTO Orders (order_id, orderdate, status, customer_number) VALUES (1, '2020-10-26', 'NEW', 1);
INSERT INTO Orders (order_id, orderdate, status, customer_number) VALUES (2, '2021-11-11', 'IN_PROGRESS', 2);
INSERT INTO Orders (order_id, orderdate, status, customer_number) VALUES (3, '2021-5-15', 'SHIPPED', 4);
INSERT INTO Order_Details (order_number, product_id, quantityordered, priceeach) VALUES (1, 2, 12, 17.50);
INSERT INTO Order_Details (order_number, product_id, quantityordered, priceeach) VALUES (2, 1, 15, 860.00);
INSERT INTO Order_Details (order_number, product_id, quantityordered, priceeach) VALUES (3, 4, 1, 499.99);
